/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"

#define MYBOT_BOARD_NAME "respeaker-flex-xvf3800-circular4-xiao"

#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_8
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_7
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_44
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_43
#define MYBOT_AUDIO_INPUT_SHIFT_BITS 16
#define MYBOT_AUDIO_CAPTURE_CHANNEL 0
#define MYBOT_AUDIO_DEFAULT_VOLUME 40

#define MYBOT_XVF3800_I2C_PORT I2C_NUM_0
#define MYBOT_XVF3800_I2C_SDA GPIO_NUM_5
#define MYBOT_XVF3800_I2C_SCL GPIO_NUM_6
#define MYBOT_XVF3800_I2C_SPEED_HZ 400000
#define MYBOT_AIC3104_I2C_ADDRESS 0x18
#define MYBOT_XVF3800_I2C_ADDRESS 0x2c

#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_0
#define MYBOT_XVF3800_BUTTON_POLL_INTERVAL_MS 50
#define MYBOT_XVF3800_BUTTON_LONG_PRESS_MS 3000

#endif /* MYBOT_BOARD_CONFIG_H_ */
