# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Shenzhen Xinzhi Future Technology Co., Ltd.
# Copyright (c) 2025 Project Contributors

set(MYBOT_BOARD_TARGET "esp32s3")
set(MYBOT_BOARD_SDKCONFIG_DEFAULTS "${CMAKE_CURRENT_LIST_DIR}/sdkconfig.defaults")
set(MYBOT_BOARD_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(MYBOT_BOARD_REQUIRED_CONFIGS
    CONFIG_PARTITION_TABLE_CUSTOM
    CONFIG_ESPTOOLPY_FLASHSIZE_8MB
    CONFIG_ESPTOOLPY_FLASHMODE_QIO
    CONFIG_SPIRAM
    CONFIG_SPIRAM_MODE_OCT
    CONFIG_SPIRAM_SPEED_80M
    CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG
    CONFIG_ESP_CONSOLE_SECONDARY_NONE
)
set(MYBOT_BOARD_FORBIDDEN_CONFIGS
    CONFIG_ESP_CONSOLE_UART_DEFAULT
    CONFIG_ESP_CONSOLE_UART
    CONFIG_MYBOT_CLOUD_AEC
)
set(MYBOT_BOARD_PARTITION_TABLE "partitions/v2/8m.csv")

get_filename_component(MYBOT_PLATFORM_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(MYBOT_BOARD_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/board.c"
    "${CMAKE_CURRENT_LIST_DIR}/xvf3800_hardware.c"
    "${CMAKE_CURRENT_LIST_DIR}/xvf3800_buttons.c"
    "${MYBOT_PLATFORM_ROOT}/src/drivers/audio/xvf3800_audio.c"
)
set(MYBOT_BOARD_REQUIRES
    button
    esp_driver_gpio
    esp_driver_i2c
    esp_driver_i2s
)
