/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"

#define MYBOT_BOARD_NAME "m5stack-core-s3"

#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_0
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_34
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_33
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_14
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_13

#define MYBOT_CORES3_I2C_PORT I2C_NUM_1
#define MYBOT_CORES3_I2C_SDA GPIO_NUM_12
#define MYBOT_CORES3_I2C_SCL GPIO_NUM_11
#define MYBOT_CORES3_I2C_SPEED_HZ 400000
#define MYBOT_CORES3_AXP2101_ADDRESS 0x34
#define MYBOT_CORES3_AW9523_ADDRESS 0x58
#define MYBOT_CORES3_FT6336_ADDRESS 0x38

#define MYBOT_DISPLAY_MOSI GPIO_NUM_37
#define MYBOT_DISPLAY_SCLK GPIO_NUM_36
#define MYBOT_DISPLAY_CS GPIO_NUM_3
#define MYBOT_DISPLAY_DC GPIO_NUM_35
#define MYBOT_DISPLAY_WIDTH 320
#define MYBOT_DISPLAY_HEIGHT 240

#define MYBOT_TOUCH_POLL_INTERVAL_MS 20
#define MYBOT_TOUCH_SHORT_PRESS_MIN_MS 50
#define MYBOT_TOUCH_LONG_PRESS_MS 3000

/* GC0308 DVP; XCLK is supplied by the board's external 20 MHz oscillator. */
#define MYBOT_CAMERA_D0 GPIO_NUM_39
#define MYBOT_CAMERA_D1 GPIO_NUM_40
#define MYBOT_CAMERA_D2 GPIO_NUM_41
#define MYBOT_CAMERA_D3 GPIO_NUM_42
#define MYBOT_CAMERA_D4 GPIO_NUM_15
#define MYBOT_CAMERA_D5 GPIO_NUM_16
#define MYBOT_CAMERA_D6 GPIO_NUM_48
#define MYBOT_CAMERA_D7 GPIO_NUM_47
#define MYBOT_CAMERA_VSYNC GPIO_NUM_46
#define MYBOT_CAMERA_HREF GPIO_NUM_38
#define MYBOT_CAMERA_PCLK GPIO_NUM_45
#define MYBOT_CAMERA_XCLK GPIO_NUM_NC
#define MYBOT_CAMERA_XCLK_HZ 20000000

#endif /* MYBOT_BOARD_CONFIG_H_ */
