/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_common.h"

#include <stdbool.h>

#define MYBOT_BOARD_NAME "esp32-s3-touch-amoled-1.75c"
#define MYBOT_AMOLED175_BOARD_VARIANT "c"
#define MYBOT_AMOLED175_HAS_TCA9554 0

/* mybot consumes 16 kHz mono signed 16-bit PCM. */
#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_16
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_9
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_45
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_8
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_10
#define MYBOT_AMOLED175_ES8311_ADDRESS 0x30
#define MYBOT_AMOLED175_ES7210_ADDRESS 0x80
#define MYBOT_AUDIO_DEFAULT_VOLUME 70

#define MYBOT_AMOLED175_I2C_PORT I2C_NUM_0
#define MYBOT_AMOLED175_I2C_SDA GPIO_NUM_15
#define MYBOT_AMOLED175_I2C_SCL GPIO_NUM_14
#define MYBOT_AMOLED175_I2C_SPEED_HZ 400000
#define MYBOT_AMOLED175_AXP2101_ADDRESS 0x34
#define MYBOT_AMOLED175_TCA9554_ADDRESS 0x20

#define MYBOT_AMOLED175_SPEAKER_PA GPIO_NUM_46

#define MYBOT_AMOLED175_LCD_SPI_HOST SPI2_HOST
#define MYBOT_DISPLAY_PCLK GPIO_NUM_38
#define MYBOT_DISPLAY_DATA0 GPIO_NUM_4
#define MYBOT_DISPLAY_DATA1 GPIO_NUM_5
#define MYBOT_DISPLAY_DATA2 GPIO_NUM_6
#define MYBOT_DISPLAY_DATA3 GPIO_NUM_7
#define MYBOT_DISPLAY_CS GPIO_NUM_12
#define MYBOT_DISPLAY_RESET GPIO_NUM_1
#define MYBOT_DISPLAY_WIDTH 466
#define MYBOT_DISPLAY_HEIGHT 466
#define MYBOT_DISPLAY_OFFSET_X 6
#define MYBOT_DISPLAY_OFFSET_Y 0
#define MYBOT_AMOLED175_LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define MYBOT_DISPLAY_MIRROR_X false
#define MYBOT_DISPLAY_MIRROR_Y false
#define MYBOT_DISPLAY_SWAP_XY false
#define MYBOT_DISPLAY_INVERT_COLOR false

#define MYBOT_AMOLED175_TOUCH_ADDRESS 0x5a
#define MYBOT_AMOLED175_TOUCH_RESET GPIO_NUM_2
#define MYBOT_AMOLED175_TOUCH_INTERRUPT GPIO_NUM_11
#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_0
#define MYBOT_AMOLED175_INPUT_POLL_INTERVAL_MS 20
#define MYBOT_AMOLED175_INPUT_SHORT_PRESS_MIN_MS 50
#define MYBOT_AMOLED175_INPUT_LONG_PRESS_MS 3000

#endif /* MYBOT_BOARD_CONFIG_H_ */
