/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_common.h"

#include <stdbool.h>

#define MYBOT_BOARD_NAME "sensecap-watcher"

/* The codec and mybot both use 16 kHz mono PCM on this board. */
#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_10
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_11
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_12
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_15
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_16
#define MYBOT_SENSECAP_ES8311_ADDRESS 0x30
#define MYBOT_SENSECAP_ES7243E_ADDRESS 0x28
#define MYBOT_SENSECAP_INPUT_GAIN_DB 27.0f
#define MYBOT_AUDIO_DEFAULT_VOLUME 70

#define MYBOT_SENSECAP_I2C_PORT I2C_NUM_0
#define MYBOT_SENSECAP_I2C_SDA GPIO_NUM_47
#define MYBOT_SENSECAP_I2C_SCL GPIO_NUM_48
#define MYBOT_SENSECAP_I2C_SPEED_HZ 400000
#define MYBOT_SENSECAP_TCA9555_ADDRESS 0x21

#define MYBOT_SENSECAP_EXPANDER_INPUT_MASK 0x20ffU
#define MYBOT_SENSECAP_EXPANDER_OUTPUT_MASK 0xdf00U
#define MYBOT_SENSECAP_KNOB_BUTTON_MASK (1U << 3)
#define MYBOT_SENSECAP_POWER_SD_MASK (1U << 8)
#define MYBOT_SENSECAP_POWER_LCD_MASK (1U << 9)
#define MYBOT_SENSECAP_POWER_SYSTEM_MASK (1U << 10)
#define MYBOT_SENSECAP_POWER_AI_MASK (1U << 11)
#define MYBOT_SENSECAP_POWER_CODEC_PA_MASK (1U << 12)
#define MYBOT_SENSECAP_POWER_GROVE_MASK (1U << 14)
#define MYBOT_SENSECAP_POWER_BAT_ADC_MASK (1U << 15)

#define MYBOT_SENSECAP_KNOB_A GPIO_NUM_41
#define MYBOT_SENSECAP_KNOB_B GPIO_NUM_42
#define MYBOT_SENSECAP_BUTTON_POLL_INTERVAL_MS 20
#define MYBOT_SENSECAP_BUTTON_DEBOUNCE_SAMPLES 3
#define MYBOT_SENSECAP_BUTTON_LONG_PRESS_MS 3000

#define MYBOT_DISPLAY_WIDTH 412
#define MYBOT_DISPLAY_HEIGHT 412
#define MYBOT_DISPLAY_OFFSET_X 0
#define MYBOT_DISPLAY_OFFSET_Y 0
#define MYBOT_DISPLAY_MIRROR_X false
#define MYBOT_DISPLAY_MIRROR_Y false
#define MYBOT_DISPLAY_SWAP_XY false
#define MYBOT_DISPLAY_BACKLIGHT GPIO_NUM_8

#define MYBOT_SENSECAP_LCD_SPI_HOST SPI3_HOST
#define MYBOT_SENSECAP_LCD_PCLK GPIO_NUM_7
#define MYBOT_SENSECAP_LCD_DATA0 GPIO_NUM_9
#define MYBOT_SENSECAP_LCD_DATA1 GPIO_NUM_1
#define MYBOT_SENSECAP_LCD_DATA2 GPIO_NUM_14
#define MYBOT_SENSECAP_LCD_DATA3 GPIO_NUM_13
#define MYBOT_SENSECAP_LCD_CS GPIO_NUM_45
#define MYBOT_SENSECAP_LCD_RESET GPIO_NUM_NC
#define MYBOT_SENSECAP_LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define MYBOT_SENSECAP_LCD_COMMAND_BITS 32
#define MYBOT_SENSECAP_LCD_PARAMETER_BITS 8

/* Canonical display aliases consumed by the shared SPD2010 renderer. */
#define MYBOT_DISPLAY_PCLK MYBOT_SENSECAP_LCD_PCLK
#define MYBOT_DISPLAY_DATA0 MYBOT_SENSECAP_LCD_DATA0
#define MYBOT_DISPLAY_DATA1 MYBOT_SENSECAP_LCD_DATA1
#define MYBOT_DISPLAY_DATA2 MYBOT_SENSECAP_LCD_DATA2
#define MYBOT_DISPLAY_DATA3 MYBOT_SENSECAP_LCD_DATA3
#define MYBOT_DISPLAY_CS MYBOT_SENSECAP_LCD_CS

#define MYBOT_SENSECAP_TOUCH_SDA GPIO_NUM_39
#define MYBOT_SENSECAP_TOUCH_SCL GPIO_NUM_38

#endif /* MYBOT_BOARD_CONFIG_H_ */
