/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_common.h"

#include <stdbool.h>

#define MYBOT_BOARD_NAME "m5stack-stick-s3"

/* mybot consumes 16 kHz mono signed 16-bit PCM. */
#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_18
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_17
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_15
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_14
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_16
#define MYBOT_STICKS3_ES8311_ADDRESS 0x30
#define MYBOT_STICKS3_INPUT_GAIN_DB 30.0f
#define MYBOT_AUDIO_DEFAULT_VOLUME 70
#define MYBOT_STICKS3_HARDWARE_VOLUME_SCALE_PERCENT 60

#define MYBOT_STICKS3_I2C_PORT I2C_NUM_0
#define MYBOT_STICKS3_I2C_SDA GPIO_NUM_47
#define MYBOT_STICKS3_I2C_SCL GPIO_NUM_48
#define MYBOT_STICKS3_I2C_SPEED_HZ 400000
#define MYBOT_STICKS3_M5PM1_ADDRESS 0x6e

#define MYBOT_DISPLAY_MOSI GPIO_NUM_39
#define MYBOT_DISPLAY_SCLK GPIO_NUM_40
#define MYBOT_DISPLAY_CS GPIO_NUM_41
#define MYBOT_DISPLAY_DC GPIO_NUM_45
#define MYBOT_DISPLAY_RESET GPIO_NUM_21
#define MYBOT_DISPLAY_BACKLIGHT GPIO_NUM_38
#define MYBOT_DISPLAY_WIDTH 135
#define MYBOT_DISPLAY_HEIGHT 240
#define MYBOT_DISPLAY_OFFSET_X 52
#define MYBOT_DISPLAY_OFFSET_Y 40
#define MYBOT_DISPLAY_MIRROR_X false
#define MYBOT_DISPLAY_MIRROR_Y false
#define MYBOT_DISPLAY_SWAP_XY false
#define MYBOT_DISPLAY_INVERT_COLOR true

#define MYBOT_STICKS3_LCD_SPI_HOST SPI3_HOST
#define MYBOT_STICKS3_LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define MYBOT_STICKS3_LCD_SPI_MODE 0

#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_11
#define MYBOT_STICKS3_BUTTON_LONG_PRESS_MS 3000

#endif /* MYBOT_BOARD_CONFIG_H_ */
