/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2026 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"

#define MYBOT_BOARD_NAME "atom-echos3r"

/* MyBot consumes 16 kHz mono signed 16-bit PCM. */
#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_11
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_17
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_3
#define MYBOT_AUDIO_I2S_DIN GPIO_NUM_4
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_48
#define MYBOT_AUDIO_DEFAULT_VOLUME 70

#define MYBOT_ATOM_ECHOS3R_I2C_PORT I2C_NUM_0
#define MYBOT_ATOM_ECHOS3R_I2C_SDA GPIO_NUM_45
#define MYBOT_ATOM_ECHOS3R_I2C_SCL GPIO_NUM_0
#define MYBOT_ATOM_ECHOS3R_I2C_SPEED_HZ 400000
#define MYBOT_ATOM_ECHOS3R_PA_ENABLE GPIO_NUM_18

#define MYBOT_ES8311_I2C_PORT MYBOT_ATOM_ECHOS3R_I2C_PORT
#define MYBOT_ES8311_I2C_ADDRESS 0x30
#define MYBOT_ES8311_INPUT_GAIN_DB 30.0f
#define MYBOT_ES8311_HARDWARE_VOLUME_SCALE_PERCENT 60

#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_41
#define MYBOT_ATOM_ECHOS3R_BUTTON_LONG_PRESS_MS 3000

#endif /* MYBOT_BOARD_CONFIG_H_ */
