/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#include "board_config.h"
#include "cores3_hardware.h"
#include "display/ili9342_panel.h"
#include "display/lvgl_view.h"

#include <mybot/platform/mybot_lcd.h>

#include "esp_lvgl_port.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/task.h"

#include <cstring>

#define TAG "ili9342_lvgl"
#define UI_LOCK_TIMEOUT_MS 1000
#define UI_APPLY_PERIOD_MS 50
#define UI_STACK_BYTES 7168

namespace {
struct Context {
    ili9342_panel_t lcd{};
    lv_display_t *display = nullptr;
    lv_timer_t *apply_timer = nullptr;
    mybot_lcd_content_t latest{};
    bool pending = false;
    bool accepting = false;
    bool port_started = false;
    bool cleanup_pending = false;
    unsigned users = 0;
    uint32_t flushing = 0;
};

Context context;
StaticSemaphore_t lifecycle_storage;
SemaphoreHandle_t lifecycle_mutex;
portMUX_TYPE lifecycle_init_lock = portMUX_INITIALIZER_UNLOCKED;
portMUX_TYPE snapshot_lock = portMUX_INITIALIZER_UNLOCKED;

bool lock_lifecycle() {
    portENTER_CRITICAL(&lifecycle_init_lock);
    if (!lifecycle_mutex) {
        lifecycle_mutex = xSemaphoreCreateMutexStatic(&lifecycle_storage);
    }
    SemaphoreHandle_t mutex = lifecycle_mutex;
    portEXIT_CRITICAL(&lifecycle_init_lock);
    return mutex && xSemaphoreTake(mutex, pdMS_TO_TICKS(UI_LOCK_TIMEOUT_MS)) == pdTRUE;
}

void unlock_lifecycle() {
    xSemaphoreGive(lifecycle_mutex);
}

void flush(lv_display_t *display, const lv_area_t *area, uint8_t *pixels) {
    __atomic_add_fetch(&context.flushing, 1, __ATOMIC_ACQ_REL);
    /* A single partial RGB565 buffer is regenerated by LVGL for each area.
     * Swap only here, matching the existing panel's high-byte-first SPI wire order. */
    lv_draw_sw_rgb565_swap(pixels, lv_area_get_size(area));
    esp_err_t err = esp_lcd_panel_draw_bitmap(context.lcd.panel, area->x1, area->y1, area->x2 + 1,
                                              area->y2 + 1, pixels);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "event=lcd action=flush backend=lvgl result=error error=%s",
                 esp_err_to_name(err));
        /* A failed submission has no DMA callback. Release LVGL and our teardown guard. */
        lvgl_port_flush_ready(display);
        __atomic_sub_fetch(&context.flushing, 1, __ATOMIC_RELEASE);
    }
}

bool flush_completed(esp_lcd_panel_io_handle_t io, esp_lcd_panel_io_event_data_t *event,
                     void *user) {
    (void)io;
    (void)event;
    auto *ctx = static_cast<Context *>(user);
    lvgl_port_flush_ready(ctx->display);
    /* flush_ready can let the other core submit its next stripe immediately.
     * Count outstanding callbacks so an earlier callback cannot clear its guard.
     * This decrement is the final context access before cleanup may proceed. */
    __atomic_sub_fetch(&ctx->flushing, 1, __ATOMIC_RELEASE);
    return false;
}

void apply_snapshot(lv_timer_t *timer) {
    (void)timer;
    mybot_lcd_content_t snapshot{};
    portENTER_CRITICAL(&snapshot_lock);
    bool update = context.accepting && context.pending;
    if (update) {
        snapshot = context.latest;
        context.pending = false;
    }
    portEXIT_CRITICAL(&snapshot_lock);
    if (update) {
        mybot_lvgl_view_update(&snapshot);
    }
}

/* Called with the lifecycle mutex, without the LVGL mutex. Board/SDK reference
 * counting ensures normal mybot stop only detaches its view, preserving Wi-Fi UI. */
int release_display() {
    context.cleanup_pending = true;
    portENTER_CRITICAL(&snapshot_lock);
    context.accepting = false;
    context.pending = false;
    portEXIT_CRITICAL(&snapshot_lock);
    if (context.display) {
        if (!lvgl_port_lock(UI_LOCK_TIMEOUT_MS)) {
            return -1;
        }
        /* A failed panel/IO teardown may leave the display alive for a retry.
         * Permanently stop its refresh timer before invalidating/deleting widgets. */
        lv_display_delete_refr_timer(context.display);
        if (context.apply_timer) {
            lv_timer_delete(context.apply_timer);
            context.apply_timer = nullptr;
        }
        /* With the port locked, no new flush can start. The DMA callback needs no
         * LVGL lock, so waiting for its final context access cannot deadlock. */
        int64_t deadline = esp_timer_get_time() + UI_LOCK_TIMEOUT_MS * 1000;
        while (__atomic_load_n(&context.flushing, __ATOMIC_ACQUIRE)) {
            if (esp_timer_get_time() >= deadline) {
                lvgl_port_unlock();
                return -1;
            }
            vTaskDelay(1);
        }
        mybot_lvgl_view_destroy();
        (void)mybot_cores3_set_display_backlight(0);
        if (context.lcd.panel) {
            (void)esp_lcd_panel_disp_on_off(context.lcd.panel, false);
        }
        /* Delete IO before display: late transfer callbacks must never hold a
         * freed lv_display_t. remove_disp does not access the panel/IO handles. */
        if (mybot_ili9342_panel_close(&context.lcd) < 0) {
            lvgl_port_unlock();
            return -1;
        }
        if (lvgl_port_remove_disp(context.display) != ESP_OK) {
            lvgl_port_unlock();
            return -1;
        }
        context.display = nullptr;
        lvgl_port_unlock();
    } else if (mybot_ili9342_panel_close(&context.lcd) < 0) {
        return -1;
    }
    if (context.port_started) {
        if (lvgl_port_deinit() != ESP_OK) {
            return -1;
        }
        context.port_started = false;
    }
    context.cleanup_pending = false;
    context.users = 0;
    __atomic_store_n(&context.flushing, 0, __ATOMIC_RELEASE);
    return 0;
}

int initialize(void **out_ctx) {
    if (!out_ctx || !lock_lifecycle()) {
        return -1;
    }
    *out_ctx = nullptr;
    if (context.cleanup_pending && release_display() < 0) {
        unlock_lifecycle();
        return -1;
    }
    if (context.users) {
        ++context.users;
        *out_ctx = &context;
        ESP_LOGI(TAG, "event=lcd action=attach backend=lvgl references=%u", context.users);
        unlock_lifecycle();
        return 0;
    }

    int result = -1;
    lvgl_port_cfg_t port_config = ESP_LVGL_PORT_INIT_CONFIG();
    port_config.task_priority = 1;
    port_config.task_affinity = 1;
    port_config.task_stack = UI_STACK_BYTES;
    port_config.task_max_sleep_ms = 500;
    port_config.timer_period_ms = 5;
    lvgl_port_display_cfg_t config{};
    esp_lcd_panel_io_callbacks_t callbacks{};
    if (mybot_ili9342_panel_open(&context.lcd, nullptr, nullptr) < 0) {
        goto done;
    }
    /* Track even a failed init: a timeout must be joined before reusing the port. */
    context.port_started = true;
    if (lvgl_port_init(&port_config) != ESP_OK) {
        goto done;
    }
    if (!lvgl_port_lock(UI_LOCK_TIMEOUT_MS)) {
        goto done;
    }
    config.io_handle = context.lcd.io;
    config.panel_handle = context.lcd.panel;
    config.buffer_size = MYBOT_DISPLAY_WIDTH * ILI9342_LCD_TRANSFER_ROWS;
    config.hres = MYBOT_DISPLAY_WIDTH;
    config.vres = MYBOT_DISPLAY_HEIGHT;
    config.color_format = LV_COLOR_FORMAT_RGB565;
    config.flags.buff_dma = true;
    config.flags.swap_bytes = false; /* The local checked flush callback owns byte swapping. */
    /* One internal DMA stripe; LVGL objects use the separate PSRAM allocator. */
    context.display = lvgl_port_add_disp(&config);
    if (!context.display) {
        lvgl_port_unlock();
        goto done;
    }
    callbacks.on_color_trans_done = flush_completed;
    if (esp_lcd_panel_io_register_event_callbacks(context.lcd.io, &callbacks, &context) != ESP_OK) {
        lvgl_port_unlock();
        goto done;
    }
    lv_display_set_flush_cb(context.display, flush);
    if (mybot_lvgl_view_create(context.display) < 0) {
        lvgl_port_unlock();
        goto done;
    }
    context.apply_timer = lv_timer_create(apply_snapshot, UI_APPLY_PERIOD_MS, nullptr);
    if (!context.apply_timer) {
        lvgl_port_unlock();
        goto done;
    }
    portENTER_CRITICAL(&snapshot_lock);
    context.latest = {};
    context.latest.screen = MYBOT_LCD_SCREEN_STARTING;
    context.pending = true;
    context.accepting = true;
    portEXIT_CRITICAL(&snapshot_lock);
    context.users = 1;
    lvgl_port_unlock();
    *out_ctx = &context;
    result = 0;
    ESP_LOGI(TAG,
             "event=lcd action=initialize backend=lvgl result=ok width=%d height=%d "
             "dma_bytes=%u ui_core=1 ui_priority=1 objects=psram",
             MYBOT_DISPLAY_WIDTH, MYBOT_DISPLAY_HEIGHT,
             (unsigned)(MYBOT_DISPLAY_WIDTH * ILI9342_LCD_TRANSFER_ROWS * sizeof(uint16_t)));
done:
    if (result < 0) {
        ESP_LOGE(TAG, "event=lcd action=initialize backend=lvgl result=error");
        if (release_display() < 0) {
            ESP_LOGE(TAG, "event=lcd action=cleanup backend=lvgl result=deferred");
        }
    }
    unlock_lifecycle();
    return result;
}

int render(void *opaque, const mybot_lcd_content_t *content) {
    if (opaque != &context || !content || content->screen < MYBOT_LCD_SCREEN_STARTING ||
        content->screen >= MYBOT_LCD_SCREEN_COUNT) {
        return -1;
    }
    mybot_lcd_content_t snapshot{};
    snapshot.screen = content->screen;
    if (snapshot.screen == MYBOT_LCD_SCREEN_IN_CONVERSATION) {
        snapshot.indicators = content->indicators;
    }
    if (snapshot.screen == MYBOT_LCD_SCREEN_PAIR_CODE) {
        size_t length = strnlen(content->pair_code, sizeof(content->pair_code));
        if (!length || length >= sizeof(content->pair_code)) {
            return -1;
        }
        for (size_t i = 0; i < length; ++i) {
            if (content->pair_code[i] < ' ' || content->pair_code[i] > '~') {
                return -1;
            }
        }
        memcpy(snapshot.pair_code, content->pair_code, length);
    }
    if (!lock_lifecycle()) {
        return -1;
    }
    int result = -1;
    portENTER_CRITICAL(&snapshot_lock);
    if (context.accepting && context.users) {
        if (memcmp(&snapshot, &context.latest, sizeof(snapshot)) != 0) {
            context.latest = snapshot;
            context.pending = true;
        }
        result = 0;
    }
    portEXIT_CRITICAL(&snapshot_lock);
    if (result == 0 && lvgl_port_task_wake(LVGL_PORT_EVENT_USER, nullptr) != ESP_OK) {
        result = -1;
    }
    unlock_lifecycle();
    return result;
}

void destroy(void *opaque) {
    if (opaque != &context || !lock_lifecycle()) {
        return;
    }
    if (context.users > 1) {
        --context.users;
        ESP_LOGI(TAG, "event=lcd action=detach backend=lvgl references=%u", context.users);
    } else if (context.users || context.cleanup_pending) {
        if (release_display() < 0) {
            ESP_LOGE(TAG, "event=lcd action=destroy backend=lvgl result=deferred");
        } else {
            ESP_LOGI(TAG, "event=lcd action=destroy backend=lvgl result=ok");
        }
    }
    unlock_lifecycle();
}

const mybot_lcd_ops_t ops = {initialize, render, destroy};
} // namespace

extern "C" const mybot_lcd_ops_t *mybot_cores3_lcd_ops(void) {
    return &ops;
}
