/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2025 Project Contributors */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_common.h"

#include <stdbool.h>

#define MYBOT_BOARD_NAME "esp-vocat"

/* The physical codec link and mybot both use 16 kHz signed 16-bit PCM. */
#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MCLK GPIO_NUM_42
#define MYBOT_AUDIO_I2S_BCLK GPIO_NUM_40
#define MYBOT_AUDIO_I2S_WS GPIO_NUM_39
#define MYBOT_AUDIO_I2S_DOUT GPIO_NUM_41
#define MYBOT_VOCAT_ES8311_ADDRESS 0x30
#define MYBOT_VOCAT_ES7210_ADDRESS 0x80
#define MYBOT_VOCAT_AUDIO_INPUT_GAIN_DB 30.0f
#define MYBOT_AUDIO_DEFAULT_VOLUME 70

#define MYBOT_VOCAT_I2C_PORT I2C_NUM_0
#define MYBOT_VOCAT_I2C_SDA GPIO_NUM_2
#define MYBOT_VOCAT_I2C_SCL GPIO_NUM_1
#define MYBOT_VOCAT_I2C_SPEED_HZ 400000
#define MYBOT_VOCAT_ES8311_PROBE_ADDRESS 0x18
#define MYBOT_VOCAT_CODEC_SELECT GPIO_NUM_48
#define MYBOT_VOCAT_POWER_CONTROL GPIO_NUM_9
#define MYBOT_VOCAT_REVISION_PROBE_DELAY_MS 50

#define MYBOT_VOCAT_V10_AUDIO_DIN GPIO_NUM_15
#define MYBOT_VOCAT_V10_AUDIO_PA GPIO_NUM_4
#define MYBOT_VOCAT_V10_LCD_RESET GPIO_NUM_3
#define MYBOT_VOCAT_V10_LCD_RESET_ACTIVE_HIGH false

#define MYBOT_VOCAT_V12_AUDIO_DIN GPIO_NUM_3
#define MYBOT_VOCAT_V12_AUDIO_PA GPIO_NUM_15
#define MYBOT_VOCAT_V12_LCD_RESET GPIO_NUM_47
#define MYBOT_VOCAT_V12_LCD_RESET_ACTIVE_HIGH true

#define MYBOT_VOCAT_LCD_SPI_HOST SPI2_HOST
#define MYBOT_VOCAT_LCD_PCLK GPIO_NUM_18
#define MYBOT_VOCAT_LCD_DATA0 GPIO_NUM_46
#define MYBOT_VOCAT_LCD_DATA1 GPIO_NUM_13
#define MYBOT_VOCAT_LCD_DATA2 GPIO_NUM_11
#define MYBOT_VOCAT_LCD_DATA3 GPIO_NUM_12
#define MYBOT_VOCAT_LCD_CS GPIO_NUM_14
#define MYBOT_VOCAT_LCD_BACKLIGHT GPIO_NUM_44
#define MYBOT_VOCAT_LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define MYBOT_VOCAT_LCD_COMMAND_BITS 32
#define MYBOT_VOCAT_LCD_PARAMETER_BITS 8

#define MYBOT_DISPLAY_WIDTH 360
#define MYBOT_DISPLAY_HEIGHT 360
#define MYBOT_DISPLAY_OFFSET_X 0
#define MYBOT_DISPLAY_OFFSET_Y 0
#define MYBOT_DISPLAY_MIRROR_X false
#define MYBOT_DISPLAY_MIRROR_Y false
#define MYBOT_DISPLAY_SWAP_XY false
#define MYBOT_DISPLAY_INVERT_COLOR true

#define MYBOT_VOCAT_TOUCH_ADDRESS 0x15
#define MYBOT_VOCAT_TOUCH_RESET GPIO_NUM_NC
#define MYBOT_VOCAT_TOUCH_INTERRUPT GPIO_NUM_10
#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_0
#define MYBOT_VOCAT_INPUT_HOLD_CHECK_INTERVAL_MS 20
#define MYBOT_VOCAT_INPUT_SHORT_PRESS_MIN_MS 50
#define MYBOT_VOCAT_INPUT_LONG_PRESS_MS 3000

#endif /* MYBOT_BOARD_CONFIG_H_ */
