#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the minimal 20 px, 4 bpp CoreS3 UI font with Pillow/FreeType.

The input is the OFL-licensed SourceHanSansSC-Normal.otf shipped with LVGL.
Only printable ASCII and the Chinese characters used by the view are embedded.
Usage: python3 scripts/generate-cores3-lvgl-font.py --font path/to/SourceHanSansSC-Normal.otf
"""

import argparse
import hashlib
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, __version__ as pillow_version, features


FONT_SHA256 = "1ee89e1669362dee13851129c0a8a791a87521eb4148e5efbf5d26596738e25b"
ROOT = Path(__file__).resolve().parent.parent
VIEW = ROOT / "components/mybot_platform/src/drivers/display/cores3_lvgl_view.cc"
OUTPUT = ROOT / "components/mybot_platform/src/drivers/display/cores3_lvgl_font.c"


def rows(values, width=12):
    return "\n".join(
        "    " + ", ".join(values[index : index + width]) + ","
        for index in range(0, len(values), width)
    )


def generate(font_path):
    if hashlib.sha256(font_path.read_bytes()).hexdigest() != FONT_SHA256:
        raise ValueError("Unexpected font revision; verify its provenance and license first")
    font = ImageFont.truetype(str(font_path), 20)
    codepoints = sorted(set(range(0x20, 0x7F)) | {ord(c) for c in VIEW.read_text() if ord(c) > 127})
    missing = bytes(font.getmask("\u0378"))
    bitmap = []
    descriptors = ["    /* Glyph ID 0 is reserved. */\n    {0},"]
    ascent = descent = 0
    for codepoint in codepoints:
        character = chr(codepoint)
        if bytes(font.getmask(character)) == missing:
            raise ValueError(f"Missing glyph U+{codepoint:04X}")
        x0, y0, x1, y1 = font.getbbox(character, anchor="ls")
        width, height = x1 - x0, y1 - y0
        if height == 0:
            width = 0
        advance = round(font.getlength(character) * 16)
        descriptors.append(
            "    /* U+%04X */\n"
            "    { .bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, "
            ".ofs_x = %d, .ofs_y = %d },"
            % (codepoint, len(bitmap), advance, width, height, x0, -y1)
        )
        if width and height:
            image = Image.new("L", (width, height))
            ImageDraw.Draw(image).text((-x0, -y0), character, font=font, fill=255, anchor="ls")
            coverage = [(pixel * 15 + 127) // 255 for pixel in image.getdata()]
            if len(coverage) % 2:
                coverage.append(0)
            bitmap.extend((coverage[i] << 4) | coverage[i + 1] for i in range(0, len(coverage), 2))
            ascent = max(ascent, -y0)
            descent = max(descent, y1)
    text = f"""/* SPDX-License-Identifier: OFL-1.1 */
/* CoreS3 UI Sans: 20 px, 4 bpp subset of Source Han Sans SC Normal.
 * Copyright 2014-2021 Adobe (http://www.adobe.com/).
 * See CORES3_FONT_LICENSE.txt. Generated by scripts/generate-cores3-lvgl-font.py.
 * Input SHA256: {FONT_SHA256}
 * Pillow {pillow_version}; FreeType {features.version("freetype2")}; {len(codepoints)} glyphs.
 */
#include "lvgl.h"

static const uint8_t glyph_bitmap[] = {{
{rows([f"0x{value:02x}" for value in bitmap])}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{chr(10).join(descriptors)}
}};

static const uint16_t unicode_list[] = {{
{rows([f"0x{codepoint - 0x20:04x}" for codepoint in codepoints])}
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x20,
        .range_length = {codepoints[-1] - 0x20 + 1},
        .glyph_id_start = 1,
        .unicode_list = unicode_list,
        .list_length = {len(codepoints)},
        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY,
    }},
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .cmap_num = 1,
    .bpp = 4,
}};

const lv_font_t mybot_cores3_font_20 = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {ascent + descent + 2},
    .base_line = {descent + 1},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};
"""
    OUTPUT.write_text(text)
    subprocess.run(["clang-format", "-i", str(OUTPUT)], check=True)
    print(f"Generated {OUTPUT.relative_to(ROOT)}: {len(codepoints)} glyphs, {len(bitmap)} bitmap bytes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=Path)
    args = parser.parse_args()
    generate(args.font)
