#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Convert the pinned local Noto emoji PNGs to constant LVGL 9 pixel arrays.

Requires Pillow and clang-format. No network or runtime image decoder is used.
Run with --check to verify source hashes and the checked-in generated output.
"""

import argparse
import hashlib
import io
import json
import subprocess
from pathlib import Path

from PIL import Image, __version__ as pillow_version


ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "components/mybot_platform/assets/ui/noto_emoji"
OUTPUT = ROOT / "components/mybot_platform/src/drivers/display/cores3_ui_assets.c"
NAMES = ("neutral", "happy", "relaxed", "thinking")


def pixel_rows(data):
    return "\n".join(
        "    " + ", ".join(f"0x{value:02x}" for value in data[start : start + 16]) + ","
        for start in range(0, len(data), 16)
    )


def generate():
    manifest = json.loads((ASSETS / "SOURCES.json").read_text(encoding="utf-8"))
    if tuple(item["name"] for item in manifest["images"]) != NAMES:
        raise ValueError("Unexpected emoji names or ordering")
    arrays = []
    descriptors = []
    for item in manifest["images"]:
        name = item["name"]
        png = (ASSETS / item["file"]).read_bytes()
        if hashlib.sha256(png).hexdigest() != item["sha256"]:
            raise ValueError(f"Unexpected source revision: {item['file']}")
        with Image.open(io.BytesIO(png)) as source:
            if source.format != "PNG" or source.size != (item["width"], item["height"]):
                raise ValueError(f"Unexpected PNG dimensions: {item['file']}")
            if source.width > 64 or source.height > 64:
                raise ValueError(f"Source requires scaling: {item['file']}")
            rgba = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
            # No mask: copy the straight-alpha channels without multiplying them.
            rgba.paste(source.convert("RGBA"), ((64 - source.width) // 2, (64 - source.height) // 2))
            # lv_color32_t is blue, green, red, alpha; ARGB names the word format.
            pixels = rgba.tobytes("raw", "BGRA")
        if len(pixels) != 16384:
            raise ValueError(f"Unexpected pixel byte count: {name}")
        arrays.append(
            f"/* {item['unicode']}; source SHA256: {item['sha256']} */\n"
            f"_Alignas(LV_DRAW_BUF_ALIGN) static const uint8_t {name}_pixels[] = {{\n"
            f"{pixel_rows(pixels)}\n}};\n"
        )
        descriptors.append(
            f"    [MYBOT_UI_EMOJI_{name.upper()}] = {{\n"
            "        .header = {\n"
            "            .magic = LV_IMAGE_HEADER_MAGIC,\n"
            "            .cf = LV_COLOR_FORMAT_ARGB8888,\n"
            "            .flags = 0,\n"
            "            .w = 64,\n"
            "            .h = 64,\n"
            "            .stride = 256,\n"
            "        },\n"
            f"        .data_size = sizeof({name}_pixels),\n"
            f"        .data = {name}_pixels,\n"
            "    },"
        )
    text = """/* SPDX-License-Identifier: OFL-1.1 */
/* Rasterized Noto Color Emoji glyphs; Copyright 2021 Google Inc. All Rights Reserved.
 * See assets/ui/noto_emoji/LICENSE.txt and SOURCES.json for license and source hashes.
 * Generated by scripts/generate-cores3-ui-assets.py. Do not edit.
 * BGRA byte order, straight alpha; each 64x61 PNG is padded to 64x64 without scaling.
 */
#include "cores3_ui_assets.h"

"""
    text += "\n".join(arrays)
    text += "\nstatic const lv_image_dsc_t emoji_images[MYBOT_UI_EMOJI_COUNT] = {\n"
    text += "\n".join(descriptors) + "\n};\n\n"
    text += """const lv_image_dsc_t *mybot_cores3_ui_emoji(mybot_ui_emoji_t emoji) {
    if ((unsigned)emoji >= MYBOT_UI_EMOJI_COUNT) {
        emoji = MYBOT_UI_EMOJI_NEUTRAL;
    }
    return &emoji_images[emoji];
}
"""
    return subprocess.run(
        ["clang-format", f"--assume-filename={OUTPUT}"],
        input=text,
        text=True,
        capture_output=True,
        check=True,
    ).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the generated file is current")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("CoreS3 emoji arrays are out of date; run this script without --check")
        print(f"Verified four emoji arrays: 65536 pixel bytes; Pillow {pillow_version}")
    else:
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}: 65536 pixel bytes; Pillow {pillow_version}")


if __name__ == "__main__":
    main()
