/* SPDX-License-Identifier: Apache-2.0 */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"

#define MYBOT_BOARD_NAME "zhengchen-1.54tft-ml307"

#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MIC_WS GPIO_NUM_4
#define MYBOT_AUDIO_I2S_MIC_BCLK GPIO_NUM_5
#define MYBOT_AUDIO_I2S_MIC_DIN GPIO_NUM_6
#define MYBOT_AUDIO_I2S_SPK_DOUT GPIO_NUM_7
#define MYBOT_AUDIO_I2S_SPK_BCLK GPIO_NUM_15
#define MYBOT_AUDIO_I2S_SPK_WS GPIO_NUM_16

#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_0
#define MYBOT_VOLUME_UP_BUTTON_GPIO GPIO_NUM_10
#define MYBOT_VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define MYBOT_DISPLAY_MOSI GPIO_NUM_41
#define MYBOT_DISPLAY_SCLK GPIO_NUM_42
#define MYBOT_DISPLAY_RESET GPIO_NUM_45
#define MYBOT_DISPLAY_DC GPIO_NUM_40
#define MYBOT_DISPLAY_CS GPIO_NUM_21
#define MYBOT_DISPLAY_BACKLIGHT GPIO_NUM_20

#define MYBOT_ML307_RX GPIO_NUM_11
#define MYBOT_ML307_TX GPIO_NUM_12

#endif /* MYBOT_BOARD_CONFIG_H_ */
