/* SPDX-License-Identifier: Apache-2.0 */
#ifndef MYBOT_BOARD_CONFIG_H_
#define MYBOT_BOARD_CONFIG_H_

#include "driver/gpio.h"
#include "driver/spi_common.h"

#define MYBOT_BOARD_NAME "zhengchen-1.54tft-wifi"

#define MYBOT_AUDIO_SAMPLE_RATE 16000
#define MYBOT_AUDIO_I2S_MIC_WS GPIO_NUM_4
#define MYBOT_AUDIO_I2S_MIC_BCLK GPIO_NUM_5
#define MYBOT_AUDIO_I2S_MIC_DIN GPIO_NUM_6
#define MYBOT_AUDIO_I2S_SPK_DOUT GPIO_NUM_7
#define MYBOT_AUDIO_I2S_SPK_BCLK GPIO_NUM_15
#define MYBOT_AUDIO_I2S_SPK_WS GPIO_NUM_16

#define MYBOT_BOOT_BUTTON_GPIO GPIO_NUM_0
#define MYBOT_VOLUME_UP_BUTTON_GPIO GPIO_NUM_10
#define MYBOT_VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define MYBOT_DISPLAY_MOSI GPIO_NUM_41
#define MYBOT_DISPLAY_SCLK GPIO_NUM_42
#define MYBOT_DISPLAY_RESET GPIO_NUM_45
#define MYBOT_DISPLAY_DC GPIO_NUM_40
#define MYBOT_DISPLAY_CS GPIO_NUM_21
#define MYBOT_DISPLAY_BACKLIGHT GPIO_NUM_20
#define MYBOT_DISPLAY_WIDTH 240
#define MYBOT_DISPLAY_HEIGHT 240
#define MYBOT_DISPLAY_OFFSET_X 0
#define MYBOT_DISPLAY_OFFSET_Y 0
#define MYBOT_DISPLAY_MIRROR_X false
#define MYBOT_DISPLAY_MIRROR_Y false
#define MYBOT_DISPLAY_SWAP_XY false
#define MYBOT_DISPLAY_INVERT_COLOR true
#define MYBOT_DISPLAY_SPI_HOST SPI3_HOST
#define MYBOT_DISPLAY_SPI_MODE 3
#define MYBOT_DISPLAY_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define MYBOT_DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define MYBOT_LVGL_OPS_NAME mybot_esp32s3_lcd_ops

#endif /* MYBOT_BOARD_CONFIG_H_ */
